// Stub data — no real film titles. All invented for design purposes.
window.FILMS = [
  {
    id: "ciudad-electrica",
    title: "Ciudad Eléctrica",
    titleLines: ["CIUDAD", "ELÉCTRICA"],
    director: "Mariela Costas",
    year: 2026,
    durationMin: 138,
    age: "14",
    genre: "Thriller neo-noir",
    rating: 4.7,
    formats: ["IMAX", "DOLBY", "VOSE"],
    tag: "ESTRENO",
    synopsis: "Una detective de Lima persigue una serie de apagones programados que parecen anunciar algo más grande que una falla en la red. Una historia de luces, lluvia y nadie en casa.",
    cast: ["Lucía Mendieta", "Andrés Vélez", "Tomás Iriarte"],
    poster: "linear-gradient(135deg,#FF2E78 0%, #7A0830 50%, #00A4BF 100%)",
  },
  {
    id: "el-ultimo-acto",
    title: "El Último Acto",
    titleLines: ["EL ÚLTIMO", "ACTO"],
    director: "Iván Salazar",
    year: 2026,
    durationMin: 114,
    age: "12",
    genre: "Drama",
    rating: 4.2,
    formats: ["DOLBY", "DOBLADA", "VOSE"],
    tag: "EN CARTELERA",
    synopsis: "Una compañía de teatro se enfrenta a su última función después de cuarenta años en cartel. Un retrato íntimo del oficio.",
    cast: ["Patricia Vera", "Hugo Mariscal"],
    poster: "linear-gradient(135deg,#F5A524 0%, #7A0830 60%, #1C1C20 100%)",
  },
  {
    id: "la-hora-azul",
    title: "La Hora Azul",
    titleLines: ["LA HORA", "AZUL"],
    director: "Ren Higa",
    year: 2026,
    durationMin: 124,
    age: "14",
    genre: "Ciencia ficción",
    rating: 4.5,
    formats: ["IMAX", "VOSE"],
    tag: "PREVENTA",
    synopsis: "En el año 2061, un equipo de oceanógrafos descubre que el océano ha empezado a recordar.",
    cast: ["Mei Watanabe", "Joaquín Ríos", "Sara Olarte"],
    poster: "linear-gradient(135deg,#00D6F5 0%, #006A7D 50%, #050506 100%)",
  },
  {
    id: "vinilo-roto",
    title: "Vinilo Roto",
    titleLines: ["VINILO", "ROTO"],
    director: "Camila Bedoya",
    year: 2026,
    durationMin: 96,
    age: "12",
    genre: "Comedia romántica",
    rating: 3.9,
    formats: ["DOBLADA", "VOSE"],
    tag: "EN CARTELERA",
    synopsis: "Dos coleccionistas de vinilos compiten por la misma rareza y terminan compartiendo más que tocadiscos.",
    cast: ["Daniela Pinto", "Marco Liendo"],
    poster: "linear-gradient(135deg,#FF7AAE 0%, #FF2E78 50%, #F5A524 100%)",
  },
  {
    id: "la-tercera-fila",
    title: "La Tercera Fila",
    titleLines: ["LA TERCERA", "FILA"],
    director: "Esteban Quirós",
    year: 2026,
    durationMin: 108,
    age: "16",
    genre: "Suspenso",
    rating: 4.1,
    formats: ["VOSE"],
    tag: "EN CARTELERA",
    synopsis: "Cuatro extraños descubren que llevan años sentándose en las mismas butacas. Y que eso no es coincidencia.",
    cast: ["Renata Solís", "Bruno Cárdenas"],
    poster: "linear-gradient(135deg,#7A0830 0%, #1C1C20 60%, #00A4BF 100%)",
  },
  {
    id: "miradas-cruzadas",
    title: "Miradas Cruzadas",
    titleLines: ["MIRADAS", "CRUZADAS"],
    director: "Sofía Aramburu",
    year: 2026,
    durationMin: 132,
    age: "12",
    genre: "Drama",
    rating: 4.0,
    formats: ["VOSE"],
    tag: "PRÓXIMAMENTE",
    synopsis: "Tres parejas. Una cena. Una verdad que llevaba años esperando.",
    cast: ["Inés Carrillo", "Adrián Vega"],
    poster: "linear-gradient(135deg,#F5A524 0%, #FF2E78 100%)",
  },
];

window.SHOWTIMES = [
  { time: "14:30", format: "VOSE",    room: "Sala 4",  status: "sold" },
  { time: "17:00", format: "DOBLADA", room: "Sala 2",  status: "open" },
  { time: "20:30", format: "VOSE",    room: "Sala 4",  status: "open", premium: true },
  { time: "23:15", format: "VOSE",    room: "Sala 4",  status: "open" },
];

window.LOCATIONS = [
  "Lima Centro",
  "Miraflores",
  "San Isidro",
  "Jockey Plaza",
  "La Molina",
  "San Miguel",
];

window.DAYS = [
  { dow: "Lun", n: 19, label: "Lun 19" },
  { dow: "Hoy", n: 20, label: "Hoy 20", today: true },
  { dow: "Mié", n: 21, label: "Mié 21" },
  { dow: "Jue", n: 22, label: "Jue 22" },
  { dow: "Vie", n: 23, label: "Vie 23" },
  { dow: "Sáb", n: 24, label: "Sáb 24" },
  { dow: "Dom", n: 25, label: "Dom 25" },
];
