/**
 * Reads NG_APP_* variables from .env (and process.env) and generates
 * src/environments/env-vars.ts so Angular's esbuild bundle can include them.
 *
 * Why: Angular sets envFile:false in its Vite config, so import.meta.env is
 * never populated from .env automatically. This script bakes the values in at
 * compile time so environment.ts can validate and export them.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = process.cwd();

function parseEnvFile(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

let fileVars = {};
try {
  fileVars = parseEnvFile(readFileSync(resolve(root, '.env'), 'utf-8'));
} catch {
  // .env not found — rely on process.env only
}

// process.env takes precedence (e.g. CI/CD injects vars directly)
const merged = { ...fileVars, ...process.env };

const ngVars = Object.fromEntries(
  Object.entries(merged).filter(([k]) => k.startsWith('NG_APP_'))
);

const output = `// Auto-generated by scripts/generate-env-ts.mjs — do not edit manually
/* eslint-disable */
export const ENV: Record<string, string | undefined> = ${JSON.stringify(ngVars, null, 2)};
`;

writeFileSync(resolve(root, 'src/environments/env-vars.ts'), output);
console.log(
  `[generate-env-ts] Wrote ${Object.keys(ngVars).length} NG_APP_* vars to src/environments/env-vars.ts`
);
